### ISSUE TITLE
Custom type definitions don't honor respond_to?

### ISSUE THREAD

**Issue by rennhak** [simplymeasured/type-gem#2] opened 2016-10-21 15:46 UTC
Great gem, thank you for all your work on this! Here is something I noticed that could be improved, which you might find interesting. Thank you very much!
### Abstract

Newly defined custom types don't #respond_to? queries.
### Description

It seems that dynamically defined types aren't very 'polite' [1] when it comes to being user friendly. That means they don't respond to being queried from other code to see if its defined or not. eg.

``` rb
2.3.1 :001 > require 'type'
 => true
2.3.1 :002 > Type.scalar( :Filename ).from( String ) do
2.3.1 :003 >     validate do |input|
2.3.1 :004 >       input.kindof?( String )
2.3.1 :005?>     end
2.3.1 :006?>   end
 => #<Type::Definition::Scalar:0x9727d48 @name=:Filename, @validators=[#<Proc:0x981d16c@/home/br/.rvm/gems/ruby-2.3.1@heracles/gems/type-0.2.0/lib/type/builtin/scalar.rb:87>, #<Proc:0x9727ab4@(irb):3>], @castors=[#<Proc:0x981d144@/home/br/.rvm/gems/ruby-2.3.1@blah/gems/type-0.2.0/lib/type/builtin/scalar.rb:90>], @parent=#<Type::Definition::Scalar:0x981d39c @name=:String, @validators=[#<Proc:0x981d16c@/home/br/.rvm/gems/ruby-2.3.1@blah/gems/type-0.2.0/lib/type/builtin/scalar.rb:87>], @castors=[#<Proc:0x981d144@/home/br/.rvm/gems/ruby-2.3.1@blah/gems/type-0.2.0/lib/type/builtin/scalar.rb:90>]>>
2.3.1 :007 > p Type.respond_to? :Filename
false
 => false 
2.3.1 :008 > p Type.const_defined? :Filename
true
 => true 
```

This isn't a big deal in terms of 'bug', but could behave better to make Type more user friendly. 
### Synopsis
- I suggest that dynamic types correctly define `#respond_to_missing?( method, *arguments )` to deal with this problem.
### Reference

[1] http://blog.marc-andre.ca/2010/11/15/methodmissing-politely/

**Comment by yaauie** [comment] 2016-12-07 00:36
@rennhak I'm sorry for the late response; your issue was created while I was on vacation and got lost in the flood. I'm closing this issue as "by design" per the following:

After you defined the new custom type (`Type::Filename`), `Type` still doesn't respond to `Filename` and is correctly reporting so.

~~~ ruby
require 'type'

Type.scalar( :Filename ).from( String ) do
  validate do |input|
    input.kind_of?( ::String )
  end
end

puts Type.respond_to? :Filename #=> false
puts Type.Filename('asdf') #!> NoMethodError: undefined method `Filename' for Type:Module
~~~

But it _does_ respond to `Filename?` (for detection) and `Filename!` (for casting) and correctly reports that it does so:

~~~ ruby
require 'type'

Type.scalar( :Filename ).from( String ) do
  validate do |input|
    input.kind_of?( ::String )
  end
end

puts Type.respond_to? :Filename? #=> true
puts Type.Filename?('/foo/bar') #=> true
puts Type.Filename?(17)
puts Type.respond_to? :Filename! #=> true
puts Type.Filename!('/foo/bar') #=> "/foo/bar"
puts Type.Filename!(17) #=> "17"
~~~

Additionally, your `Type.scalar( :Filename ).from( String )` creates a new `Type::Definition` that inherits validation from `Type::String`, so by the time your validator is called, it has already been validated by `Type::String`'s validator.

**Closed by yaauie** 2016-12-07 00:36 UTC
